### PR TITLE
Fix recreated-database bug and issue with -D General

### PR DESCRIPTION
**Pull request by Gumnos**
This should fix Issue #4 (both pieces). It may be inelegant, but it solves the issues I had.

### CODE REVIEW

**Comment by buhtz** [comment]
What is the status of the PR? It is quite old.

**Comment by Gumnos** [comment]
As far as I know, it hasn't been merged.

**Comment by buhtz** [comment]
Of course it isn't merged because I can see that here on GitHub. ;)

The question is if someone is working on it? Or is there a reason why isn't it merged?

**Comment by Gumnos** [comment]
Heh, as the one submitting the patch, I can only give a "the pull-request I submitted solved the issues I was having", so you're welcome to go rogue like me and run a patched version. I haven't heard anything privately from @iamaziz beyond the silence in this issue.  And that said, while TermFeed is nice I was mostly tinkering with it and have since settled on `rss2email` which just puts them in my inbox (affording me all the power of my mail-filters for processing RSS).

**Pull request closed without merging**
